# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=80)),
                ('imgsrc', models.CharField(max_length=100)),
                ('root', models.IntegerField(null=True, verbose_name=0)),
                ('number', models.IntegerField(null=True, verbose_name=0)),
                ('contribution', models.IntegerField(null=True, verbose_name=0)),
                ('point', models.IntegerField(null=True, verbose_name=0)),
            ],
        ),
    ]
